### ISSUE TITLE
Enable Travis testing

### ISSUE THREAD

**Issue by staticfloat** [dmbates/FLAC.jl#5]
I believe you just need to login to Travis and "turn on" this repository.  [Here are the docs](https://docs.travis-ci.com/user/getting-started/), for reference.

**Comment by dmbates** [comment]
I did enable travis testing and then made a token commit that just involved adding spaces so the travis run would be triggered.  Right now `Pkg.test("FLAC")` fails for me and also fails on travis because the current release of `FileIO` doesn't relate a `.flac` extension to this package.

**Comment by staticfloat** [comment]
I've requested a new release [here](https://github.com/JuliaIO/FileIO.jl/issues/60).

**Comment by dmbates** [comment]
@staticfloat Thanks for requesting the release.
